### PR TITLE
Remove first break line in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by abdonrd**
Example: https://raw.githubusercontent.com/PolymerElements/polymer-starter-kit/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by rictic** [comment]
How about calling `trimLeft` on the string instead?

**Comment by abdonrd** [comment]
@rictic both options are okey for me. :)

Tell me if you want that I update the PR.

**Comment by rictic** [comment]
Eh, not worth the hassle I suppose. Thanks for the PR!

**Comment by abdonrd** [comment]
Your welcome! :)

**Pull request merged**
