### PR TITLE
Black list for upcoming catalog

### PR DESCRIPTION
**Pull request by samuelli**

### CODE REVIEW

**Comment by rictic** [comment]
@tjsavage @cdata @notwaldorf 

Have we discussed how we intend to write and keep readme's up to date in the new catalog world?

**Comment by tjsavage** [comment]
The aim is to only have to really update the README when a major feature is added that we want to make a demo for.

**Comment by rictic** [comment]
In the long term then do we want to just disable README generation entirely?

**Comment by samuelli** [comment]
@rictic: Yep. I'm not sure what else Tedium is used for? Ideally it should be reserved for challenges unique to the Polymer team. Problems which other component authors might feel should be addressed in another way.

**Comment by rictic** [comment]
Cool, yeah I agree with that perspective a lot.

**Review by rictic — APPROVED** [review]

**Comment by rictic** [comment]
LGTM.

**Comment by samuelli** [comment]
FYI, I don't have access to merge

**Comment by rictic** [comment]
oic. merged!

**Pull request merged**
