### PR TITLE
cache node_modules

### PR DESCRIPTION
**Pull request by dfreedm**
Worth discussing if this is a good idea.
Polymer has this enabled, seems to be quite beneficial

### CODE REVIEW

**Comment by rictic** [comment]
Code looks good, my only concern is that forever-caching is going to bite us eventually. e.g. the chrome driver will probably eventually need to be updated to stay compatible with chrome

**Comment by dfreedm** [comment]
I'll test a few elements and see how they go!

**Comment by TimvdLippe** [comment]
If I understand the caching correctly, `npm` will first look up the to-be-downloaded version using the registry. Then it will check the cache if that specific version is already installed. If yes, then use that version. Else download a fresh one from the internet. I have not yet been able to come up with a testing process to verify this behaviour.

**Comment by TimvdLippe** [comment]
The cache was reenabled on the PSK which led to `npm install` of just 29.17 seconds! https://travis-ci.org/PolymerElements/polymer-starter-kit/jobs/127479281#L221
Previously it took 88.94 seconds (https://travis-ci.org/PolymerElements/polymer-starter-kit/jobs/123966654#L219), which is a 75% speed up. The builds on the official Polymer repo do not seem to be broken and are faster too. https://travis-ci.org/Polymer/polymer/builds/125128347#L239 took just 5.71 (!) seconds to `npm install`.

**Comment by TimvdLippe** [comment]
I have now configured Travis to also cache global node_modules, notably `bower` and `web-component-tester`. This means that whenever you do `npm install -g bower web-component-tester` it will not install everything including Selenium, but just use the cache.

You can see the speed difference from before the cache https://travis-ci.org/TimvdLippe/iron-lazy-pages/builds/159818426#L306 to after using the cache https://travis-ci.org/TimvdLippe/iron-lazy-pages/builds/159819491#L304-L315

It is a 33% speed increase for these builds, which I think is also substantial.

**Comment by TimvdLippe** [comment]
Oops I forgot to include the configuration. These are the two lines that are required:

``` yaml
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules/web-component-tester
    - $(npm config get prefix)/lib/node_modules/bower
```

**Comment by TimvdLippe** [comment]
All right, @rictic talked about this on Slack and while we expected the caching to work properly, I decided to actually test on a dummy repository.

First I installed `bower@1.7.0`: https://travis-ci.org/TimvdLippe/test-travis-cache/builds/160669657
Then I installed `bower@1.7.1`: https://travis-ci.org/TimvdLippe/test-travis-cache/builds/160670044
And then I installed `bower`: https://travis-ci.org/TimvdLippe/test-travis-cache/builds/160670486
And another run with just `bower`: https://travis-ci.org/TimvdLippe/test-travis-cache/builds/160670713

Conclusion: `npm install -g` checks which version is currently installed and will overwrite if a newer version is found. That is then uploaded to the cache and fetched for the next time. Therefore I think it is safe to add the global packages to the cache.

For the local cache however (e.g. just `node_modules`) I have not tested it, so that might have to be removed.

**Pull request closed without merging**
