### PR TITLE
Initial update to using typescript 2.0

### PR DESCRIPTION
**Pull request by rictic**
This is a noop change, just shuffles around how we do our typings.

Main changes:
- use @types from npm instead of typings
- use `include` in tsconfig instead of the more awkward `filesGlob` + `files`

### CODE REVIEW

**Comment by valdrinkoshi** [comment]
I can `npm i && npm run build`, so LGTM 👍

**Comment by valdrinkoshi** [comment]
After a successful install and build, I get this error:

```
valdrin$ node tedium.js 
Discovering repos in PolymerElements...  [=============================================] 100%
Cloning repos...                         [=--------------------------------------------] 3%


Error: authentication required but no callback set
    at Error (native)
```

**Comment by valdrinkoshi** [comment]
@rictic ping, any update on this?

**Comment by rictic** [comment]
Do you also get that error on master?

**Comment by valdrinkoshi** [comment]
On master I cannot successfully `npm install` since I get:

```
> tedium@1.0.0 build /Users/valdrin/dev/tedium
> tsc

node_modules/dom5/dom5.d.ts(12,77): error TS1110: Type expected.
node_modules/dom5/dom5.d.ts(51,76): error TS1110: Type expected.
node_modules/dom5/dom5.d.ts(76,73): error TS1110: Type expected.
node_modules/dom5/dom5.d.ts(108,21): error TS1110: Type expected.
```

**Comment by rictic** [comment]
The code is still in a usable state after that error. Typescript still outputs the right code when it encounters errors. Give it a shot!

Sorry for the vague responses. I'm not sure if I have much time to debug this right now.

I'm happy to give guidance if you're willing to push this forward though.

**Comment by valdrinkoshi** [comment]
Yes, same error running `node tedium.js`, I must have entered in some weird case with my github authentication, but I'll debug this on my own (not related to the PR).
Regarding this PR it still LGTM since it installs and build w/o errors 👍

**Pull request merged**
