### PR TITLE
Polymer 2.0 whatever

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by rictic** [comment]
This won't be merged, it's for the example of how tedium

**Comment by notwaldorf** [comment]
Thanks! Gotted, bookmarked, closed! 🍰

**Comment by notwaldorf** [comment]
Wait wasn't this supposed to not get merged?

**Comment by rictic** [comment]
This branch started out as just a helpful set of documentation but ended up getting a bunch of really nice features. All this code is too useful, I'm not updating the automatically-running version with this yet though, as it is still specialized to 2.0-preview which is a very temporary thing :pray:

**Pull request merged**
